#!/usr/bin/env node
/**
 * Build the llms.txt documentation files.
 *
 * Three files, one source of truth:
 *
 * - `docs/static/llms.txt`      — hand-written, concise. **The source.** Not
 *                                 generated by this script; it only copies it.
 * - `packages/core/llms.txt`    — a copy of the above, shipped to npm so an
 *                                 agent can read the API of the exact version
 *                                 it has installed, out of `node_modules`,
 *                                 rather than guessing from a hosted page that
 *                                 describes a different release.
 * - `docs/static/llms-full.txt` — generated from every page in `docs/docs`, in
 *                                 sidebar order.
 *
 * Impulse publishes one package, so unlike `inertia`'s version of this script
 * there is no per-adapter slice. Add one here if that ever changes.
 *
 * Run with `pnpm run build:llms`, and re-run after editing any page or
 * changing the public API. CI fails on a dirty diff over the generated files.
 */

import { copyFileSync, existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(here, '..')
const docsDir = join(repoRoot, 'docs')
const docsContentDir = join(docsDir, 'docs')
const staticDir = join(docsDir, 'static')
const corePkgDir = join(repoRoot, 'packages', 'core')

// Page order comes from docs/sidebars.ts, so the rendered site and this file
// cannot drift. The sidebar is TypeScript and this repo supports Node 20, so
// it is read as text rather than imported. Every quoted string that is not a
// `type`, `label`, or import specifier is a doc id.
const sidebarsPath = join(docsDir, 'sidebars.ts')

function readSidebarDocIds(source) {
  const body = source
    .split('\n')
    .filter((line) => !line.trimStart().startsWith('import '))
    .join('\n')
    .replace(/\b(type|label)\s*:\s*(['"])(?:(?!\2).)*\2/g, '')
  const ids = []
  for (const match of body.matchAll(/(['"])((?:(?!\1).)+)\1/g)) {
    ids.push(match[2])
  }
  if (ids.length === 0) {
    throw new Error(`[build-llms] no doc ids found in ${sidebarsPath}`)
  }
  return ids
}

const PAGES = readSidebarDocIds(readFileSync(sidebarsPath, 'utf8'))

/** Strip the leading YAML frontmatter block from a markdown page. */
function stripFrontmatter(md) {
  if (!md.startsWith('---')) return md
  const end = md.indexOf('\n---', 3)
  if (end === -1) return md
  const after = md.indexOf('\n', end + 4)
  return after === -1 ? '' : md.slice(after + 1)
}

/** Drop the `import` block an MDX page may carry, so the output is prose. */
function stripMdxImports(md) {
  const lines = md.split('\n')
  let i = 0
  while (i < lines.length) {
    const line = lines[i]
    if (line.startsWith('import ') || line.trim() === '') {
      i++
      continue
    }
    break
  }
  return lines.slice(i).join('\n')
}

/**
 * Turn Docusaurus admonitions into plain markdown.
 *
 * These pages lean on `:::danger` and `:::warning` for the things that fail
 * silently, and those are exactly the parts an agent reading this file most
 * needs. Left as `:::` fences they are noise; as a bold label and a blockquote
 * they survive as emphasis in any plain-text reader.
 */
function expandAdmonitions(md) {
  return md.replace(
    /^:::(note|tip|info|warning|danger|caution)(?:[ \t]+([^\n]*))?\n([\s\S]*?)^:::[ \t]*$/gm,
    (_match, kind, title, body) => {
      const label = title?.trim()
        ? `${kind.toUpperCase()} — ${title.trim()}`
        : kind.toUpperCase()
      const quoted = body
        .replace(/^\s*\n/, '')
        .trimEnd()
        .split('\n')
        .map((line) => (line.trim() === '' ? '>' : `> ${line}`))
        .join('\n')
      return `> **${label}**\n>\n${quoted}`
    },
  )
}

function resolveDocPath(id) {
  const mdx = join(docsContentDir, `${id}.mdx`)
  if (existsSync(mdx)) return mdx
  const md = join(docsContentDir, `${id}.md`)
  if (existsSync(md)) return md
  throw new Error(
    `[build-llms] no page for id "${id}" — looked for ${id}.mdx and ${id}.md ` +
      `in ${docsContentDir}. Every id in docs/sidebars.ts needs a file.`,
  )
}

function renderPage(id) {
  const raw = readFileSync(resolveDocPath(id), 'utf8')
  return expandAdmonitions(stripMdxImports(stripFrontmatter(raw))).trimEnd()
}

function buildLlmsFull() {
  const header = [
    '# Impulse — full documentation',
    '',
    '> Every documentation page, in sidebar order. Generated from docs/docs by',
    '> scripts/build-llms.mjs — do not edit by hand.',
    '',
    '> Source: https://github.com/rootnative/impulse',
    '> Site:   https://rootnative.github.io/impulse/',
    '',
    '---',
    '',
  ].join('\n')

  return header + PAGES.map(renderPage).join('\n\n---\n\n') + '\n'
}

const llmsTxtPath = join(staticDir, 'llms.txt')
const llmsFullPath = join(staticDir, 'llms-full.txt')
const corePackageLlmsPath = join(corePkgDir, 'llms.txt')

if (!existsSync(llmsTxtPath)) {
  throw new Error(
    `[build-llms] ${llmsTxtPath} is missing. It is written by hand, not ` +
      `generated — this script only copies it into the package.`,
  )
}

console.log(`[build-llms] ${PAGES.length} pages: ${PAGES.join(', ')}`)

console.log('[build-llms] writing docs/static/llms-full.txt …')
writeFileSync(llmsFullPath, buildLlmsFull())

console.log(
  '[build-llms] copying docs/static/llms.txt → packages/core/llms.txt',
)
copyFileSync(llmsTxtPath, corePackageLlmsPath)

console.log('[build-llms] done.')
